apiVersion: v1
kind: Service
metadata:
  name: node-hello-service
spec:
  selector:
    app: node-hello
  type: NodePort
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 3000  
      nodePort: 30000  
