apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-hello
  template:
    metadata:
      labels:
        app: node-hello
    spec:
      containers:
        - name: node-hello
          image: docker.io/aarju24/node-hello-master:latest  # Fully qualified image name
          imagePullPolicy: Never  # Pull the image if not present locally

